version: '3'
services:
  todo-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/tododb
      NODE_ENV: production
      PORT: 3100
    restart: always
    container_name: todo-app-backend
    command: >
      sh -c "npx prisma migrate deploy && npm start"

    depends_on:
      - db

  
  db:
    image: postgres:latest
    container_name: todo-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/


volumes:
  postgres_data: